export let keyWords = {
  Programa: "Programa",
  Inicio: "Inicio",
  Fin: "Fin",
  DibujarCirculo: "DibujarCirculo",
  DibujarRectangulo: "DibujarRectangulo",
  DibujarTriangulo: "DibujarTriangulo",
  EliminarFigura: "EliminarFigura",
  Dormir: "Dormir",
  ROJO: "ROJO",
  AZUL: "AZUL",
  VERDE: "VERDE",
  NEGRO: "NEGRO",
  AMARILLO: "AMARILLO",
  Constante: "Constante",
}
