export let keyWords = {
  Programa: "Programa",
  Inicio: "Inicio",
  Fin: "Fin",
  DibujarCirculo: "DibujarCirculo",
  DibujarRectangulo: "DibujarRectangulo",
  DibujarTriangulo: "DibujarTriangulo",
  EliminarFigura: "EliminarFigura",
  Dormir: "Dormir",
  ROJO: "red",
  AZUL: "blue",
  VERDE: "green",
  NEGRO: "black",
  AMARILLO: "yellow",
  Constante: "Constante",
}
